### ISSUE TITLE
Dataverse URL

### ISSUE THREAD

**Issue by jjvenky** [paukes/canada-ecozone-DOM#1]
Probably better to link directly to the DOI https://doi.org/10.5683/SP2/ZRGXQ5 rather than that awkward Dataverse URL https://dataverse.scholarsportal.info/dataset.xhtml?persistentId=doi:10.5683/SP2/ZRGXQ5 since it could change if the scholarsportal system changes.

**Comment by paukes** [comment]
Very good point. Will update here and in manuscript
